### ISSUE TITLE
Enable app insights

### ISSUE THREAD

**Issue by madebygps** [learntocloud/learn-to-cloud#101]
At the moment, we don't have deeper metrics in LTC because we don't have a function. Let's create a seperate app insight insights and use this to enable it https://github.com/Microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup
https://stackoverflow.com/questions/68146449/deeper-analytics-for-azure-static-web-apps

**Comment by madebygps** [comment]
Nevermind, this is up for anyone to work on.

**Comment by rishabkumar7** [comment]
When using dot-env to store connection string for app insights, ran into an issue.
error:
```
Module not found: Error: Can't resolve 'fs' in 'E:\GitHub\learn-to-cloud\node_modules\dotenv\lib'
Module not found: Error: Can't resolve 'path' in 'E:\GitHub\learn-to-cloud\node_modules\dotenv\lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
client (webpack 5.75.0) compiled with 2 errors
```

**Comment by rishabkumar7** [comment]
So after going over the stackoverflow answer [here](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5)

> Answer : I was also getting these error's when upgrading from webpack v4 to v5. Resolved by making the following changes to webpack.config.js
added resolve.fallback property
removed node property
```
{
resolve: {
  modules: [...],
  fallback: {
    "fs": false,
    "tls": false,
    "net": false,
    "path": false,
    "zlib": false,
    "http": false,
    "https": false,
    "stream": false,
    "crypto": false,
    "crypto-browserify": require.resolve('crypto-browserify'), //if you want to use this module also don't forget npm i crypto-browserify 
  } 
},
entry: [...],
output: {...},
module: {
  rules: [...]
},
plugins: [...],
optimization: {
  minimizer: [...],
},
// node: {
//   fs: 'empty',
//   net: 'empty',
//   tls: 'empty'
// },
}
```

But we don't have a `webpack.config.js` in our project (pardon my ignorance as I am new to React and JS)

Researched a bit about how we can have a `webpack` config, and found this - https://github.com/facebook/docusaurus/issues/2097

**Comment by madebygps** [comment]
closing since we are no longer going to implement this
