### ISSUE TITLE
Move `Contributors` page to new directory for support in docusausrus

### ISSUE THREAD

**Issue by rishabkumar7** [learntocloud/learn-to-cloud#115]
Have to move `contributors.md` to new directory `pages` for support in docusaurus.
Also have to update the GH Action since `Contributors.md` gets automatically generated everyday

**Comment by rishabkumar7** [comment]
The action we currently have, that generates the `Contributors.md`, doen't provide valid md to be rendered by docusaurus.
Getting this error:
```
SyntaxError: E:\GitHub\learn-to-cloud\src\pages\Contributors.md: JSX value should be either an expression or a quoted JSX text. (13:21)
  11 |     <td align="center" style="word-wrap: break-word; width: 150.0; height: 150.0">
  12 |         <a href="https://github.com/madebygps">
> 13 |             <img src=https://avatars.githubusercontent.com/u/6733686?v=4 width="100;"  style="border-radius:50%;align-items:center;justify-content:center;overflow:hidden;padding-top:10px" alt=Gwyneth Peña-Siguenza/>
     |                      ^
  14 |             <br />
  15 |             <sub style="font-size:14px"><b>Gwyneth Peña-Siguenza</b></sub>
  16 |         </a>
  ```

**Comment by rishabkumar7** [comment]
Looking into this - https://github.com/marketplace/actions/contribute-list

**Comment by madebygps** [comment]
I think this can be closed?

**Comment by rishabkumar7** [comment]
`Contributors.md` is not being generated, will take a look at the action

**Comment by rishabkumar7** [comment]
Using both the new and the old action causes the docusaurus render to fail, since new action needs a comment in the `Contributors.md` file to add automated contributors, these comment don't render:
```
SyntaxError: /Users/rishabkumar/GitHub/learn-to-cloud/src/pages/Contributors.md: Unexpected token (206:1)
  204 |     </td></tr>
  205 | </table>
> 206 | <!-- readme: contributors -end -->
      |  ^
  207 |     </MDXLayout>
  208 |   )
  209 | };
```

**Comment by rishabkumar7** [comment]
I am going to move `Contributors.md` back to root while we figure this out as it is causing the staging preview to fail

**Comment by rishabkumar7** [comment]
Added another job to the contributor action to generate and SVG, which now renders in the docusaurus page 😅 
The SVG is created by the action and can be found here `static/img/CONTRIBUTORS.svg`
