### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by azgcloudev** [learntocloud/learn-to-cloud#120]
Is your feature request related to a problem? Please describe.
No.

Describe the solution you'd like
Translation to spanish.

Additional context
Initiate translation to spanish

**Comment by rishabkumar7** [comment]
@azgcloudev awesome, I am getting some docs updates in for the instruction based on the new directory structure

**Comment by rishabkumar7** [comment]
@azgcloudev the wiki has been updated for new instructions - https://github.com/learntocloud/learn-to-cloud/wiki/Language-Support-for-LTC

And there is already a locale available for `es` in staging branch:
https://github.com/learntocloud/learn-to-cloud/tree/staging/i18n/es/docusaurus-plugin-content-docs/current

**Comment by azgcloudev** [comment]
Phase 0 translated - see PR #122

**Comment by rishabkumar7** [comment]
Thanks @azgcloudev will review tonight

**Comment by madebygps** [comment]
closing as this was merged
