### ISSUE TITLE
Translation to ukrainian

### ISSUE THREAD

**Issue by byfilin** [learntocloud/learn-to-cloud#128]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Translation to Ukrainian

**Additional context**
I would love to translate this repo. Very useful and concise info

**Comment by byfilin** [comment]
Hey. Working on it. 
@rishabkumar7 Can you please tell me, should I make changes in "docusaurus.config.js" to add UA (ukrainian)? 
Or just docs folder for translation

**Comment by rishabkumar7** [comment]
@byfilin thanks for contributing.
You can start with creating the required directories to support UA. here is how it should look
``` bash
└── learntocloud
    ├── docs
    ├── 
    └── i18n
        ├── ua
            ├── docusaurus-plugin-content-docs
                  ├── current
                       ├── Phase1
 ```

**Comment by madebygps** [comment]
merged. Thank you for the massive contribution :D
