### ISSUE TITLE
Wrong link in Phase 5

### ISSUE THREAD

**Issue by byfilin** [learntocloud/learn-to-cloud#131]
**Describe the bug**
Wrong link in Phase 5 on Thunder CTF line

**To Reproduce**
1. Go to https://learntocloud.guide/docs/phase5/
2. Scroll down to Resources
3. Click on ThunderCTF
4. It leads to AWS training site

**Expected behavior**
i assume that link should lead to https://thunder-ctf.cloud

**Comment by rishabkumar7** [comment]
opened a PR - #132
