### ISSUE TITLE
Welcome[Doc] typo & Contribution to Phase one [ in linux command section ]

### ISSUE THREAD

**Issue by Shyamjitripathi** [learntocloud/learn-to-cloud#151]
@rishabkumar7 @madebygps 

Bug :  On welcome page in Phases table [ optional should be " Optional" ]
Improvement : In phase 1 linux bash page want to add [ linux command mind map Link ]
[Linux Mind Map ](https://xmind.app/m/WwtB/)

**Screenshots**
![image](https://user-images.githubusercontent.com/59613166/235084085-3a518a87-94df-48fe-87bc-4c40e721fa3d.png)
![image](https://user-images.githubusercontent.com/59613166/235084849-cd16f14a-d6fa-466c-b188-cfe6bf1618b4.png)

**Comment by madebygps** [comment]
thank you for the issues. We are content at the moment with Linux content and resources. Thank you.
