### ISSUE TITLE
theme icon Overflow in hambourger  

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [learntocloud/learn-to-cloud#159]
![Screenshot from 2023-05-11 01-49-48](https://github.com/learntocloud/learn-to-cloud/assets/85225156/b0464a1b-2e1f-40d4-9ed2-cf3b1935eab9)

I want to change the theme icon place for the smaller screen and want to make it responsive.

**Comment by rishabkumar7** [comment]
Hi @Vikash-8090-Yadav thanks for helping, please let me know if you need anything.
Here is how to run the project locally - https://github.com/learntocloud/learn-to-cloud/wiki/Local-dev-server-setup

**Comment by azgcloudev** [comment]
@rishabkumar7  I did fix this using custom CSS, also fix the size of the items in the navbar when the screen size is smaller

New Layout:
<img width="1440" alt="image" src="https://github.com/learntocloud/learn-to-cloud/assets/72358828/28dc38a9-3840-4406-a3e0-88e82addb03f">

<img width="1027" alt="image" src="https://github.com/learntocloud/learn-to-cloud/assets/72358828/a5456546-c6d2-47aa-a57b-467529be5f58">

I made changes to position the hamburger to the left
<img width="869" alt="image" src="https://github.com/learntocloud/learn-to-cloud/assets/72358828/ac286ac7-5144-488c-8dd3-824472a35396">

<img width="694" alt="image" src="https://github.com/learntocloud/learn-to-cloud/assets/72358828/a23e7b04-850a-4510-81d7-e250e4a3dfb9">



current layout:
<img width="1022" alt="image" src="https://github.com/learntocloud/learn-to-cloud/assets/72358828/3bf5e02c-3ac0-45ec-8cee-6365f44ebfab">

<img width="873" alt="image" src="https://github.com/learntocloud/learn-to-cloud/assets/72358828/d0c8b9d2-f0a1-43a6-acfc-500268ff082f">

<img width="877" alt="image" src="https://github.com/learntocloud/learn-to-cloud/assets/72358828/649c46a1-8239-4895-a3f4-f882ffe50cf3">

**Comment by azgcloudev** [comment]
PR #163

**Comment by madebygps** [comment]
resolved in PR

**Comment by rishabkumar7** [comment]
The theme toggle should be in the navbar, looks kinda weird
<img width="1149" alt="image" src="https://github.com/learntocloud/learn-to-cloud/assets/45825464/af3e2f1d-c200-4044-9fac-421d9b52a983">

**Comment by azgcloudev** [comment]
@rishabkumar7 that is something I notice docusaurus put it there by default, I will try to see if I can move it somewhere.

**Comment by azgcloudev** [comment]
@rishabkumar7  fix in PR #169

**Comment by madebygps** [comment]
thank you, closing now :)
