### ISSUE TITLE
ADD hover transition to Get Started button as well as Homecards.

### ISSUE THREAD

**Issue by Sakhi29** [learntocloud/learn-to-cloud#170]
**Is your feature request related to a problem? Please describe.**
The Get Started button when hovered should display a transition, also the homecards when hovered for clicking should have some sort of transition on perspective of better UI

**Describe the solution you'd like**
As I mentioned I want Get started button and homecards to have transition when hovered

**Describe alternatives you've considered**

**Additional context**
I would like to work upon this issue please assign it to me.

**Comment by madebygps** [comment]
Hi @Sakhi29 can you please clarify which buttons and cards you are referring to?

Thank you :)

**Comment by Sakhi29** [comment]
Hello @madebygps I am extremely sorry for I have mistakenly opened a wrong issue in here. It was supposed to be opened in another repository. I am sorry for the inconveniences I have caused. Right now I am closing this issue and am willing to definitely to contribute to your repo shortly. Thanks!
