### ISSUE TITLE
Add discord logo in navbar section instead of just text.

### ISSUE THREAD

**Issue by kaushal1717** [learntocloud/learn-to-cloud#171]
**Is your feature request related to a problem? Please describe.**
The link to the Discord channel is in text.
<img width="1424" alt="Screenshot 2023-10-27 at 7 23 54 PM" src="https://github.com/learntocloud/learn-to-cloud/assets/121810303/bb73b82b-529c-4c6f-9c9a-1a544f8ba224">

**Describe the solution you'd like**
I would like to add a logo of Discord instead of text as shown in the screenshot like we used for github there.

I would request @madebygps to take a look on the issue and assign it to me.

**Comment by madebygps** [comment]
Hi there, we will keep it as is, thank you.
