### ISSUE TITLE
Phase 5 link redirection

### ISSUE THREAD

**Issue by ArtistYay** [learntocloud/learn-to-cloud#183]
The attack detection fundamentals for AWS & Azure in Phase 5: Cloud Security Fundamentals in the resource table, points to f-secure threats & research blog site instead of the three-part series. I've searched the site and it seems the article doesn't exist. <img width="1363" alt="Screenshot 2024-01-09 at 2 50 54 PM" src="https://github.com/learntocloud/learn-to-cloud/assets/72479678/d4f05fc3-131a-4b51-9d5b-b4726fa5d190">

**Comment by azgcloudev** [comment]
Doing quick investigation 

```
HTTP/2 301 
server: AkamaiGHost
content-length: 0
location: https://blog.f-secure.com/category/threats-research/
expires: Thu, 11 Jan 2024 00:04:32 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Thu, 11 Jan 2024 00:04:32 GMT
X-Firefox-Spdy: h2
```

```
HTTP/2 301 
server: AkamaiGHost
content-length: 0
location: https://blog.f-secure.com/category/threats-research/
expires: Thu, 11 Jan 2024 00:06:40 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Thu, 11 Jan 2024 00:06:40 GMT
X-Firefox-Spdy: h2
```

Both URLs get a redirection to https://blog.f-secure.com/category/threats-research/

This URLs were added in the commit https://github.com/learntocloud/learn-to-cloud/commit/bcbdde3fc1b972fe056bc03668954e4c15a6c76a


@rishabkumar7 @madebygps  I cannot tag the original owner, so not sure if those steps are not valid anymore if the link is redirected.

**Comment by ArtistYay** [comment]
Reached out to Day about it on Discord. I think he's looking into it.

**Comment by ethanolivertroy** [comment]
This has been updated. This issue can be closed.
The links now navigate correctly to:
https://labs.withsecure.com/publications/attack-detection-fundamentals-2021-azure-lab-1
and
https://labs.withsecure.com/publications/attack-detection-fundamentals-2021-aws-lab-1

**Comment by madebygps** [comment]
appreciate you!
