### ISSUE TITLE
Implement Grafana Container for Monitoring

### ISSUE THREAD

**Issue by rishabkumar7** [learntocloud/learn-to-cloud#191]
**Is your feature request related to a problem? Please describe.**
We want to monitor learntocloud and define the cloud. We will be using Grafana to create monitoring dashboards gathering data from Azure Monitor and App Insights.

**Describe the solution you'd like**
This issues is the first step, creating a Grafana Docker Image that will be launched a Azure App Service (Container).

**Comment by rishabkumar7** [comment]
Published the docker image to docker hub `rishabkumar7/grafana-container`

**Comment by azgcloudev** [comment]
@rishabkumar7  I can take this

**Comment by rishabkumar7** [comment]
@azgcloudev I have published the image to docker hub - `rishabkumar7/grafana-container`
I will create another issue, as I am currently using `root` user to install `nginx` onto the `grafana` container.
I don't know if there is a way to bypass that.
