### ISSUE TITLE
Add Azure Monitor as Data Source in Grafana

### ISSUE THREAD

**Issue by rishabkumar7** [learntocloud/learn-to-cloud#194]
**Is your feature request related to a problem? Please describe.**
Implementing Grafana to monitor the LTC and DTC web-apps.
Already have the container apps running for Grafana, need to add Azure Monitor as data source.

**Describe the solution you'd like**
Add Azure Monitor as data source by creating Service Principle for the apps.

**Additional context**
I don't have the right permissions to create the Service Principle.

**Comment by madebygps** [comment]
updated your permissons, can you try now please

**Comment by rishabkumar7** [comment]
Was able to create a Service Principle with new assigned permissions, Azure Monitor added as Data Source in Grafana.

**Comment by madebygps** [comment]
beautiful
