### ISSUE TITLE
Contributors page leads to a 404 error if: opened in a new tab/refreshed

### ISSUE THREAD

**Issue by jawadzizo** [learntocloud/learn-to-cloud#196]
I am not a web developer, pardon my ignorance if I am mistaken, or if the issue is insignificant.

**Describe the bug**
We get a 404 error if we try to open the contributors page in a new tab, or if we refresh a working contributors page.

**To Reproduce**
1. Go to: https://learntocloud.guide/
2. Scroll down to the footer
3. Open the contributors page in a new tab
4. We get a 404 error

or

1. Go to: https://learntocloud.guide/
2. Scroll down to the footer
3. Click on Contributors
4. Refresh
5. We get a 404 error

or simply

1. Go to: https://learntocloud.guide/Contributors
2. We get a 404 error

**Expected behavior**
A non-404 error.

**Screenshots**
Screenshot:
![404](https://github.com/learntocloud/learn-to-cloud/assets/36828298/9a30bd20-cef6-402b-8707-2b4313763beb)

Recording: https://www.awesomescreenshot.com/video/25040772?key=3ed65b1851ca58da2eeecf12588ec560

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 121

**Comment by rishabkumar7** [comment]
Thank @jawadzizo for reporting the issue, working on it #197

**Comment by rishabkumar7** [comment]
The issue has been fixed, and the page is now link to user's GitHub profile, rather than an SVG image.
https://learntocloud.guide/contributors
<img width="1897" alt="image" src="https://github.com/learntocloud/learn-to-cloud/assets/45825464/672d7d53-5ffc-4d22-ab22-ad0fcc5740cb">
