### ISSUE TITLE
Homepage 404-Error when Translating from English to Other Languages, and Vice Versa.

### ISSUE THREAD

**Issue by jawadzizo** [learntocloud/learn-to-cloud#198]
**Describe the bug**
When we are on the homepage and trying to change the language, we get a 404 error. The same thing happens when translating other languages' homepage into English.

**To Reproduce**
1. Go to https://learntocloud.guide/
2. Click on 'English' in the navigation bar
3. Choose any language
4. 404 error (must land on https://learntocloud.guide/fr/Welcome instead of https://learntocloud.guide/fr/)

**Expected behavior**
A functional homepage in the chosen language.

__________________________________

**To Reproduce**
1. Go to https://learntocloud.guide/fr/Welcome
2. Click on 'Français' in the navigation bar
3. Choose English
4. 404 error (must land on https://learntocloud.guide/ instead of https://learntocloud.guide/Welcome/)

**Expected behavior**
A functional homepage in the English language.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 121

**Comment by rishabkumar7** [comment]
Thank you for creating this issue, will be working on this.
