### ISSUE TITLE
GOLANG PATH INCLUSION

### ISSUE THREAD

**Issue by jesse-crypted** [learntocloud/learn-to-cloud#200]
**Just a suggestion.**
I would love to suggest an inclusion of the Golang learning path in the project site to give people an opportunity to learn apart from python

**Comment by madebygps** [comment]
hmmm... @rishabkumar7 thoughts?

**Comment by rishabkumar7** [comment]
@jesse-crypted is this specifically for a project (like phase 2 Capstone or phase 4 Capstone project) or just in general to have a Golang path?

**Comment by jesse-crypted** [comment]
Just in general to have a Golang path for those interested in learning
Golang over Python

**Comment by madebygps** [comment]
Closing for now, feel free to reopen when you have time.
