### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by g-now-zero** [learntocloud/learn-to-cloud#216]
**Describe the bug**
On the Learn to Cloud Guide Phase 1 page, the "Build and access the lab" links to "4-buildthelab.md" which results in a "Page Not Found" error. Specifically, the link https://learntocloud.guide/phase1/4-buildthelab.md is broken.

**To Reproduce**
1. Go to 'https://learntocloud.guide/phase1/'
2. Look for the "Build and access the lab" section
4. See "Page Not Found" error

**Expected behavior**
The link should direct to found page.

Desktop (please complete the following information):
- OS: Linux Pop OS
- Browser: Firefox

**Comment by madebygps** [comment]
thank you thank you! resolved. https://github.com/learntocloud/learn-to-cloud/commit/afaffeb6c355ee7f650cabe19ef6d372c8317b4b
