### ISSUE TITLE
Video Link in Phase 0 Documentation Unavailable

### ISSUE THREAD

**Issue by alexfrnn** [learntocloud/learn-to-cloud#219]
### Description
The video link "este vídeo" on line 12 of the Phase 0 README in Portuguese is currently unavailable on YouTube. When trying to access the content, it leads to an error page.

## Expected Behavior
The link should direct to the video content for Youtube video related to phase 0.
## Actual Behavior
The link leads to an error page, indicating that the content is unavailable.
## Steps to Reproduce the Problem

  1. Navigate to the following link: [Phase 0 README in Portuguese](https://github.com/learntocloud/learn-to-cloud/blob/74568a5653017c833aa4a48f19424fbff1dc0102/i18n/pt/docusaurus-plugin-content-docs/current/phase0/README.md)
  2. Go to line 12 and click on the video link: [Youtube video suggested](https://youtu.be/awLnur5Yt9o)
  3. Observe the error page indicating that the content is unavailable.

## Specifications

  - Version:
  - Platform: Microsoft Edge
  - Subsystem:

### Additional Information
Please verify and update the link accordingly. Thank you!

Image attached for reference:
![image](https://github.com/user-attachments/assets/d714c72c-d922-4453-a9f6-30e12b8e7950)

**Comment by madebygps** [comment]
Resolved in latest :) thank you for submitting this issue. Change should be live soon.
