### ISSUE TITLE
 Broken Link in Phase 5

### ISSUE THREAD

**Issue by oyogbeche** [learntocloud/learn-to-cloud#222]
**Describe the bug**
I noticed a broken link on the website that points to example.com instead of the intended article.

**To Reproduce**
1. Go to 'https://learntocloud.guide/phase5/'
2. Click on 'Cloud Security Breaches and Vulnerabilities: 2021 in Review'
3. Notice that it redirects to https://example.com instead of the expected page.

**Expected behavior**
The link should redirect to the intended article. 'https://blog.christophetd.fr/cloud-security-breaches-and-vulnerabilities-2021-in-review/'

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 131

**Comment by madebygps** [comment]
hello @oyogbeche thank you for submitting this issue, we are currently working on an entire update to this phase, be on the lookout for that. In the meantime, I will make this update.

**Comment by madebygps** [comment]
https://github.com/learntocloud/learn-to-cloud/commit/79c5c0cd4610d6459d832bf6c77f493645ae902a resolved
