### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by flaviorescia** [learntocloud/learn-to-cloud#28]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Translate this project to other countries, in my case Brazil

**Describe alternatives you've considered**
I work with Cloud here in Brazil, and I can knew your project today, I will understand your html format and create a PR for it. What about?

**Additional context**
Congrats for you project, simples, put so funcional.

**Comment by madebygps** [comment]
Flávio thank you so much for offering this. Is there anything you need from us to get started on this?

**Comment by rishabkumar7** [comment]
@flaviorescia thanks for takinng the initiative on this
Here are the some instructions to get started with setiing up `docsify` locally
- It is recommended to install docsify-cli globally:
`npm i docsify-cli -g`

After forking the project and cloning the repo, you can start the docsify local server by `docsify serve`
(Make sure you are in the root dir of the project)

You will have a dev server running on port 3000

Also for the language support, you will have to create a different director, I would suggest it under the root.

**Comment by joseasync** [comment]
May I help?

**Comment by rishabkumar7** [comment]
Sure thing, let me know if you run into any blockers @joseasync

**Comment by joseasync** [comment]
Hi @rishabkumar7, I added the Codeowners with you and Gwyn. 
As you don't have it on the main yet, please can you add you both as PR reviewers on the [PR#36](https://github.com/learntocloud/learn-to-cloud/pull/36) 

On the [branch protection rules](https://github.com/learntocloud/learn-to-cloud/settings/branches) you can set the codeowners as default reviewers, automating this part if you wish.

**Comment by ViniViniAntunes** [comment]
I am continuing the translation into Portuguese

**Comment by rishabkumar7** [comment]
Phase 2 has been merged #65

**Comment by ViniViniAntunes** [comment]
Phase 3 translated.

**Comment by rishabkumar7** [comment]
Phase 3 had been merged #66

**Comment by rishabkumar7** [comment]
phase 4 merged #67

**Comment by ViniViniAntunes** [comment]
[Phase 5 translated](https://github.com/learntocloud/learn-to-cloud/pull/69)

**Comment by rishabkumar7** [comment]
@ViniViniAntunes I made some comments about the sidebar, once those changes are in, will merge the PR

**Comment by madebygps** [comment]
@rishabkumar7  I think this might be done?

**Comment by rishabkumar7** [comment]
Yep all 5 phases merged
