### ISSUE TITLE
Translation to French

### ISSUE THREAD

**Issue by Wintermute21** [learntocloud/learn-to-cloud#35]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Translation to French

**Additional context**
Happy to dedicate my evening hours to translating into French.

**Comment by rishabkumar7** [comment]
This is being worked on #44

**Comment by madebygps** [comment]
Closed as PR was merged

**Comment by rishabkumar7** [comment]
reopening this, as we still need translations for the Welcome and Phase 0

**Comment by garciadrl** [comment]
How can I help ? I speak french.

**Comment by rishabkumar7** [comment]
hi @garciadrl thanks for reaching out, there is a file [learn-to-cloud](https://github.com/learntocloud/learn-to-cloud)/[fr](https://github.com/learntocloud/learn-to-cloud/tree/main/fr)/phase0/ which needs translation

**Comment by arushmangal** [comment]
I shall have it done within 2-3 hours if you give me the green light to work on this!

**Comment by arushmangal** [comment]
I have made the PR with the translation of the README.md file
