### ISSUE TITLE
Incorrect docsify command

### ISSUE THREAD

**Issue by azgcloudev** [learntocloud/learn-to-cloud#38]
## Expected Behavior
- create a local server

## Actual Behavior
- getting error message

## Steps to Reproduce the Problem

1. Access project root directory
2. Run docsify server

## Specifications

- Wiki affected: Local dev server setup

## Suggested solution
- Correct command to start the server is 'docsify serve'

**Comment by rishabkumar7** [comment]
@azgcloudev thank you, I made a typo 😅

**Comment by rishabkumar7** [comment]
wiki page updated ✅
