### ISSUE TITLE
Error loading URL of Content

### ISSUE THREAD

**Issue by mysterioux** [learntocloud/learn-to-cloud#47]
**Describe the bug**
Link to GPS's AWS CDA Notes on Phase 3 Not Working

**To Reproduce**
1. Go to https://learntocloud.guide/#/phase3/README?id=how-does-this-phase-apply-to-cloud
2. Click on GPS's AWS CDA Notes under the Resource Table
3. One Drive displays and error

**Expected behavior**
The link was supposed to show the notes made by the author when preparing for his/her CDA exam with Amazon.

**Additional context**
But it appears the file has either been deleted or remove or transferred to another location and the link was not updated

**Comment by madebygps** [comment]
Thank you, I've updated that.
