### ISSUE TITLE
On clicking logo it takes me to 404 page

### ISSUE THREAD

**Issue by imshashvatgupta** [learntocloud/learn-to-cloud#52]
## Expected Behavior
After hitting the url https://learntocloud.guide/ when I drag it down the webpage and then again click on the Learn to Cloud logo it should take me to the https://learntocloud.guide(homepage).
## Actual Behavior
After hitting the URL https://learntocloud.guide/ when I drag down and then again click on the Learn to Cloud logo it should take me to the https://learntocloud.guide(homepage) instead of that, it takes me to this URL (https://learntocloud.guide/undefined) that gives me a 404 page.
## Steps to Reproduce the Problem

  1. Open the website https://learntocloud.guide/ 
  2. Drag down the page a little bit.
  3. Click on the Learn to Cloud logo.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by madebygps** [comment]
Thank you :) I've resolved this in latest update.
