### ISSUE TITLE
Translation to Indonesian

### ISSUE THREAD

**Issue by danidanz** [learntocloud/learn-to-cloud#59]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Translation to Indonesian.

**Additional context**
I'm happy to help to initiate Indonesian translation. I will dedicate my time at least two hours/day until it's completed.

**Comment by madebygps** [comment]
Hi there, we have docs on how to get started here https://github.com/learntocloud/learn-to-cloud/wiki/Language-Support-for-LTC

**Comment by madebygps** [comment]
closing, please feel free to reopen if/when you have the bandwitdh :)
