### ISSUE TITLE
Translation - Nepali Language 

### ISSUE THREAD

**Issue by srishtipoudel** [learntocloud/learn-to-cloud#68]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Translation to Nepali language

**Describe alternatives you've considered**
I came across your guide earlier and the material came out to be really helpful. I want to contribute to this repo by translating it to my native language. 

**Additional context**
Thank you for making learning cloud so easier !

- [x]  README.md
- [x]  phase0
- [x]  phase1
- [x]  phase2
- [x]  phase3
- [x]  phase4
- [x]  phase5
- [ ]  Contributing.md
- [ ]  License 
- [ ]  coverpage.md
- [ ]  navbar.md
- [ ]  sidebar.md

**Comment by rishabkumar7** [comment]
Thank you @srishtipoudel for taking the initiative

**Comment by srishtipoudel** [comment]
- [x]  README.md
- [ ]  phase0
- [ ]  phase1
- [ ]  phase2
- [ ]  phase3
- [ ]  phase4
- [ ]  phase5

**Comment by sarthakregmi** [comment]
i want to work on phase 4 and 5 .

**Comment by srishtipoudel** [comment]
@rishabkumar7 could we have hactoberfest label in this issue?

**Comment by rishabkumar7** [comment]
@srishtipoudel Added the label, also you don't have to update the `Contributors.md` as it is automatically generated by a GitHub Action

**Comment by madebygps** [comment]
Thank you for your contribution :)
