### ISSUE TITLE
README.md links broken

### ISSUE THREAD

**Issue by folusomaine** [learntocloud/learn-to-cloud#84]
**Describe the bug**
Links for Phases 0 - 5 returns 404

Page not found

**To Reproduce**
1. Click on links for Phases 0 - 5
2. See error

**Expected behavior**
Links should point to the new URLs after migration [e.g. `Phase0` - ` https://learntocloud.guide/docs/phase0/`]

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [108]

**Comment by rishabkumar7** [comment]
@folusomaine did you mean the READMEs in GitHub repo (browsing via GitHub) not the website right?

**Comment by folusomaine** [comment]
ah yes - GitHub.
LTC GitHub.

**Comment by rishabkumar7** [comment]
Thanks for confirming @folusomaine 
I have updated the links - https://github.com/learntocloud/learn-to-cloud/commit/d3f55323743b203d80f83c1870d63cd6e58d671a
