### ISSUE TITLE
Create Status Dashboard

### ISSUE THREAD

**Issue by madebygps** [learntocloud/learn-to-cloud#86]
Create a Status dashboard we can serve at learntocloud.guide/status or status.learntocloud.guide

Should display

- Any alerts that have not been resolved in past 24 hours.
- Optional but would be cool (research) cost for past 31 days.

**Comment by madebygps** [comment]
This is the API we can use to generate reports https://learn.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update?tabs=Python#exportcreateorupdatebyresourcegroup

**Comment by yvesDenis** [comment]
@madebygps If you don't mind I can carry out this activity.

**Comment by Zolfen** [comment]
is this backlog purposefully embedded to LTC main page or just a mixup?

**Comment by madebygps** [comment]
@Zolfen yes on purpose :) the reason is for people to be able to see WIP and comment on any work they would like to contribute to. 

@yvesDenis @rishabkumar7 can you both work on this one?

**Comment by azgcloudev** [comment]
@madebygps is this issue solved?

**Comment by rishabkumar7** [comment]
@azgcloudev no not yet, I did some work on migrating the domain to Cloudflare, as we want to use Cloudflare Analytics as opposed to Google Analytics.
Also, the Grafana instance is running, but we are not displaying any dashboards yet, since Cloudflare Analytics are not configured yet.

**Comment by azgcloudev** [comment]
@rishabkumar7 I can help on this, we can coordinate in discord

**Comment by madebygps** [comment]
closing, no longer planned.
