### ISSUE TITLE
Create API that will show Cloud Definition on homepage

### ISSUE THREAD

**Issue by madebygps** [learntocloud/learn-to-cloud#87]
On homepage display a random cloud definition from cloud dictionary. Keep cloud dictionary and LTC as separate projects. Just expose random quote via an API e.g clouddictionary.com/api/random

**Comment by madebygps** [comment]
Okay, here is API call for random definition, https://clouddictionary.azurewebsites.net/api/GetRandomDefinition

need to add like 10 more definition but ready to integrate

**Comment by rishabkumar7** [comment]
Awesome, I am building the API fetch component, could enable `cors` since getting this error
```
localhost/:1 
Access to fetch at 'https://clouddictionary.azurewebsites.net/api/GetRandomDefinition' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by madebygps** [comment]
My bad, added https://learntocloud.guide and http://learntocloud.guide to CORS. Works now?

**Comment by rishabkumar7** [comment]
Still figuring out the react component to display this on homepage, the API works

**Comment by madebygps** [comment]
Shipped!
