### ISSUE TITLE
Implement CI/CD for staging enviroment

### ISSUE THREAD

**Issue by madebygps** [learntocloud/learn-to-cloud#88]

**Comment by madebygps** [comment]
Right now, our CI/CD on main will push to a staging environment and generate a preview site. Can we configure a dev branch that can do this too?

**Comment by yvesDenis** [comment]
Hi ! I think I can give a hand on this activity. Any volunteer to give me the context in details? Thx in advance :)

**Comment by madebygps** [comment]
HI @yvesDenis thanks for volunteering for this. @rishabkumar7 already has more than 50% done for this task so he is going to take care of this. Please feel free to take a look at the rest issues and comment on what you're interested in.

**Comment by rishabkumar7** [comment]
We did a live working session for this feature - https://youtu.be/Wfo4uIUq1FM

**Comment by madebygps** [comment]
Done
