### ISSUE TITLE
Implement search feature

### ISSUE THREAD

**Issue by madebygps** [learntocloud/learn-to-cloud#89]
At the moment it's not possible to search for anything on LTC. I know Docusauras has this feature, let's implement it.

**Comment by ethanolivertroy** [comment]
DocSearch is free for open source projects: https://docsearch.algolia.com/apply/

**Comment by rishabkumar7** [comment]
Hi @197naveen ,

Thanks for contributing, could you reference the GitHub secret `ALGOLIA_API_KEY`, I will save it in the GitHub Secrets.
And then you can reference it in the project/code.
Once you create a PR, SWA(Static Web Apps) will create preview, so you will have a live environment to test it.

Let me know if you have any questions.

Thank you :)

**Comment by madebygps** [comment]
@rishabkumar7 API info is now available. Check your email for invite.

**Comment by madebygps** [comment]
Hi @197naveen we now have API info, are you still interested in working on this? If so by when do you think you'd be able to? We are looking to have this complete within the next 2 weeks, so if that's possible with you, we would love to have you contribute :)

**Comment by 197naveen** [comment]
Hi @madebygps ,

I'm beginner for development area and interested in contributing to this feature. and i will try to complete within 3 weeks after getting the API.

Thanks
https://twitter.com/197naveen

**Comment by BrianCollet** [comment]
@madebygps @rishabkumar7 

I would love to contribute to this feature if @197naveen is no longer interested.

Thanks!

**Comment by madebygps** [comment]
hi @BrianCollet thank you for volunteering for this, I've added the ALGOLIA_API_KEY as a secret so you should be able to use it.

**Comment by madebygps** [comment]
hi @197naveen  thank you for the interest here, @BrianCollet  is going to cover this issue has he has more availability, and we need this implemented sooner than later. There's plenty more issues available and we always add more so please stay tuned :)

**Comment by 197naveen** [comment]
Hi @madebygps  @BrianCollet ,
Sure Brian will work on this feature. and I will work on other issues.

**Comment by madebygps** [comment]
Thank you @BrianCollet for the work here. @rishabkumar7 once you push to main please close this :)

**Comment by rishabkumar7** [comment]
This is released here #126
