### ISSUE TITLE
Implement embed feature

### ISSUE THREAD

**Issue by madebygps** [learntocloud/learn-to-cloud#90]
Figure out how to embed YT videos into guide instead of it just being a link.

**Comment by rishabkumar7** [comment]
It looks pretty good on the website:
![Image](https://user-images.githubusercontent.com/45825464/211433828-fa4d7d0c-2a96-4893-8c71-1227dd0f87d6.png)

But won't look good on the readme in GH.

**Comment by madebygps** [comment]
That's okay. Let's prioritize site over GitHub readme.
